"""Create self-contained initial sources for commands in the user config.

The package keeps these files only as installation templates.  Once copied to
``~/.config/unlaw/commands``, each command runs without importing Unlaw.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

_ROOT = Path(__file__).parent

# Exact hashes of command files generated by earlier Unlaw releases.  Only
# these known files may be upgraded automatically; user edits are preserved.
LEGACY_SOURCE_HASHES: dict[str, set[str]] = {
    "git": {
        "02a1e26e4489d9c66d81f6699bf22c8661431332ded7967d022e0934c73292c8",
        "0b57d2be0a4ab8ab8fc7f55e91c6d37a5ca1ca14e747fd61a618f9666714a823",
    },
    "tg": {
        "d228c0425aebe27fe3e211415b10e18bbc80bc4f7ab5b4c0b9f55913a6e1a1a3",
    },
}

_PRELUDE = r'''# Unlaw command source. Edit freely: this file has no runtime dependency on Unlaw.
from __future__ import annotations

import copy
import json
import os
import tempfile
import tomllib
from pathlib import Path


DEFAULT_CONFIG = {
    "core": {"color": True, "verbose": False, "command_timeout": 0, "show_timing": False},
    "aliases": {},
    "storage": {"root": "data"},
    "git": {"auto_push": True},
    "projects": {
        "python": {"environment": "auto", "initialize_git": False},
        "rust": {"initialize_git": False},
        "cpp": {"standard": 20, "initialize_git": False},
    },
    "mac": {"executable": "macos-harness", "timeout": 30},
    "todo": {"vault_path": "~/aiwork/data-obsidian", "file": "TODO.md", "completed_column": "Completed"},
    "capture": {"camera_device": "0", "audio_device": "0", "screen_audio": True, "show_clicks": True},
    "games": {"difficulty": "normal"},
    "apps": {
        "spotify": "Spotify", "editor": "Zed", "spotify_autoplay_delay": 2.0,
        "lofi_url": "https://lofi-engine.vercel.app/", "youtube_url": "https://www.youtube.com/",
    },
    "telegram": {"chat_id": "", "api_base": "https://api.telegram.org", "keychain_service": "unlaw.telegram"},
    "lm": {
        "base_url": "http://127.0.0.1:1234/v1", "model": "auto",
        "system_prompt": "You are a concise and practical local assistant.", "temperature": 0.7,
        "timeout": 120,
    },
}


class ConfigError(ValueError):
    pass


def config_dir() -> Path:
    base = Path(os.environ.get("XDG_CONFIG_HOME", "~/.config")).expanduser()
    return base / "unlaw"


def templates_dir() -> Path:
    return config_dir() / "templates"


def _deep_merge(base: dict, override: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in override.items():
        result[key] = _deep_merge(result[key], value) if isinstance(value, dict) and isinstance(result.get(key), dict) else copy.deepcopy(value)
    return result


def load_config() -> dict:
    path = config_dir() / "config.toml"
    try:
        with path.open("rb") as handle:
            configured = tomllib.load(handle)
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise ConfigError(f"Could not read {path}: {error}") from error
    return _deep_merge(DEFAULT_CONFIG, configured)


def storage_path(*parts: str) -> Path:
    configured = Path(str(load_config()["storage"]["root"])).expanduser()
    root = configured if configured.is_absolute() else config_dir() / configured
    return root.joinpath(*parts)


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    raise ConfigError(f"Unsupported configuration value: {value!r}")


def _serialize_table(table: dict, path: tuple[str, ...], lines: list[str]) -> None:
    if path:
        if lines and lines[-1] != "":
            lines.append("")
        lines.append("[" + ".".join(path) + "]")
    for key, value in table.items():
        if not isinstance(value, dict):
            lines.append(f"{key} = {_toml_value(value)}")
    for key, value in table.items():
        if isinstance(value, dict):
            _serialize_table(value, (*path, key), lines)


def set_config_value(dotted: str, value: object) -> None:
    config = load_config()
    parts = dotted.split(".")
    table = config
    for part in parts[:-1]:
        table = table.setdefault(part, {})
        if not isinstance(table, dict):
            raise ConfigError(f"Configuration key is not a table: {part}")
    table[parts[-1]] = value
    lines: list[str] = []
    _serialize_table(config, (), lines)
    root = config_dir()
    root.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=root, delete=False) as handle:
            handle.write("\n".join(lines).lstrip("\n") + "\n")
            handle.flush()
            os.fsync(handle.fileno())
            temporary = Path(handle.name)
        os.replace(temporary, root / "config.toml")
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def latest_capture() -> Path | None:
    candidates = [
        path for directory in (storage_path("captures", "screenshots"), storage_path("captures", "recordings"))
        if directory.is_dir() for path in directory.iterdir() if path.is_file()
    ]
    return max(candidates, key=lambda path: path.stat().st_mtime, default=None)
'''

_COMMAND_FILES: dict[str, tuple[str, ...]] = {
    "app": ("built_in_commands/app/main.py",),
    "browser": ("desktop/launcher.py", "built_in_commands/browser/main.py"),
    "capture": ("capture.py",),
    "cpp": ("project_templates.py", "built_in_commands/cpp/main.py"),
    "game": ("games.py",),
    "git": ("built_in_commands/git/main.py",),
    "gpt": ("desktop/launcher.py", "built_in_commands/gpt/main.py"),
    "lm": ("lmstudio.py",),
    "lofi": ("desktop/launcher.py", "built_in_commands/lofi/main.py"),
    "mac": ("harness.py", "built_in_commands/mac/main.py"),
    "minecraft": ("desktop/launcher.py", "built_in_commands/minecraft/main.py"),
    "music": ("desktop/music.py",),
    "netflix": ("desktop/launcher.py", "built_in_commands/netflix/main.py"),
    "obsidian": ("desktop/launcher.py", "built_in_commands/obsidian/main.py"),
    "py": ("project_templates.py", "built_in_commands/py/main.py"),
    "rust": ("project_templates.py", "built_in_commands/rust/main.py"),
    "steam": ("desktop/launcher.py", "built_in_commands/steam/main.py"),
    "tg": ("telegram.py",),
    "todo": ("todo.py",),
    "work": ("desktop/work.py",),
    "yt": ("desktop/youtube.py",),
    "zed": ("desktop/launcher.py", "built_in_commands/zed/main.py"),
}


def _clean_fragment(source: str, *, command: str) -> str:
    removed_prefixes = (
        "from __future__ import annotations",
        "from .config import ",
        "from unlawful.config import ",
        "from unlawful.project_templates import ",
        "from unlawful.desktop.launcher import ",
        "from unlawful import harness",
        "from .capture import latest_capture",
    )
    lines = [line for line in source.splitlines() if not line.lstrip().startswith(removed_prefixes)]
    text = "\n".join(lines).strip() + "\n"
    if command == "mac":
        text = text.replace("harness.see", "see").replace("harness.key", "key")
        text = text.replace("harness.type_text", "type_text").replace("harness.click", "click")
    return text


def command_source(name: str) -> str:
    """Return the complete standalone source installed for one default command."""
    try:
        paths = _COMMAND_FILES[name]
    except KeyError as error:
        raise ValueError(f"Unknown default command: {name}") from error
    fragments = [
        _clean_fragment((_ROOT / relative).read_text(encoding="utf-8"), command=name)
        for relative in paths
    ]
    return _PRELUDE + "\n\n" + "\n\n".join(fragments)


def is_legacy_wrapper(source: str, name: str) -> bool:
    return source.strip() == (
        f"from unlawful.built_in_commands.{name}.main import main\n\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())"
    ) or source.strip() == (
        f"from unlawful.built_in_commands.{name}.main import main\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())"
    )


def is_replaceable_command_source(source: str, name: str) -> bool:
    digest = hashlib.sha256(source.encode()).hexdigest()
    return is_legacy_wrapper(source, name) or digest in LEGACY_SOURCE_HASHES.get(name, set())
