"""Create focused, self-contained sources for commands in the user config."""

from __future__ import annotations

from .command_help import COMMAND_HELP

import hashlib
import pprint
from pathlib import Path

_ROOT = Path(__file__).parent

# Exact hashes of command files generated by earlier Unlaw releases. Only
# these known files may be upgraded automatically; user edits are preserved.
LEGACY_SOURCE_HASHES: dict[str, set[str]] = {
    "app": {"fb335c5b8bd7d3038b911e4c207a0425b4467cc98ff35c7329dc626aa65673ab"},
    "browser": {
        "0562ed878703da8e4cd91fb167d1ce2c17157ff6313c996152a49ca70e097262",
        "db814ce6b36d767e3a59c0edea8e5b00b54daebc0700150019902832b6441cbe",
    },
    "capture": {"75ad32af09f41eb7cabc8870430983b271897fcf4c40e699c6ac01f12a769a04"},
    "cpp": {"5f4d547aa2220de60280b23d235da9c3cae89391b4cd4e96c0214e897a3626cb"},
    "game": {"c563e57bd7aae1e0ba1766034e60398892b3f96531e2afc6ddadc802e276ecc4"},
    "git": {
        "02a1e26e4489d9c66d81f6699bf22c8661431332ded7967d022e0934c73292c8",
        "0b57d2be0a4ab8ab8fc7f55e91c6d37a5ca1ca14e747fd61a618f9666714a823",
        "80926eabb120a6254542376c392cb33a7508b111ef224d868923263f2dd19259",
    },
    "gpt": {
        "14ce1726615c9726f9d3fd3e337273981d69a2ff22b0365f91fda93629a76677",
        "9d25f0d416407ef204e4421db5c3c4a4209111107f4ec539f6e36ea4a303ec6d",
    },
    "lm": {"e42f1097c58e1413530f9bf2146621ac300822fe5c2800ee3559ab3d8bc744f2"},
    "lofi": {
        "4c1ee273e1a07841b422f4a345d89f0c1a7078939170ba06dac41cb6847070de",
        "9880584db9736ccdca7f853bc038b2b30d215780bc263be27f0885d75159bb95",
    },
    "mac": {"50b9398c5232c08e963f7fd20ba146cc24196042f3357d243300d4dc9cce5f53"},
    "minecraft": {
        "1db1ca84feec081fec309e0c3f6c92bd482f18a33b163bf8373f5cb09bcc8baf",
        "c34fc8277f886cdcf1799ad755dfd292b4b448b99e13da71e6174a271a39767d",
    },
    "music": {"ffb785ba7985fb4d369491876e100bd7316c8e177ec22f7d363a94ba38cf585d"},
    "netflix": {
        "677928b0868c13312b6ae479b6d6de39957f92bb895da3ef559e4281d4f825c5",
        "c4a3d398021123106ae47e61971022b30c7d5482285a8ae488981f76bf07c43b",
    },
    "obsidian": {
        "41634e2cc9a843124e03fb5b8ae8a26227afb1188a321aa172eea2a1e896fad6",
        "4fc6a5ff2dddf1610e63f741f326819bd892263b04f28a5d2974c60e18fb586d",
    },
    "py": {"ab4874ea85c5eb0a81b8c030453e799c6bf480f070f326d466038773222f4927"},
    "rust": {"0ee40fad349cdb13bdb1b16e69385d2a89d54f1223e75e8053534ab9438b7e25"},
    "steam": {
        "a1850c1130f5fc5bfee70c255f03982228c6e86e591df2d656ff37326e03d6ef",
        "b37c7497b9b0a93ec182733440ae34d6a00a136510990b3c039e004a82dacbd3",
    },
    "tg": {
        "d228c0425aebe27fe3e211415b10e18bbc80bc4f7ab5b4c0b9f55913a6e1a1a3",
        "57fccff311bac90c76557a33cb75d041c570408906e1df32237141a94175aadf",
    },
    "todo": {"d74e2f777a824840c8d064c2a9237dcbfd78ed6e28cda1d3054c42f19a64b9d0"},
    "work": {"35b3d9d20deb6d2927a36446d1986439ab18184f14a67b27dc6b47eef4da8e27"},
    "yt": {
        "435ff09674eb854cd96050936f843ab83f67eec8f2fcad00566b7e099ce4a884",
        "1a1cc7ec191f33960644a15553cf02b796af6deffd5380f245e408561c8998cb",
        "4dc2aa8198cb48e36a79bbc2b801ab0405a146397e11fc030f4d92c8992654a0",
        "3350048da95a672c85208ed5710d66627807cbc62a76f8566617672092f357f2",
    },
    "zed": {
        "b38672c8a421b0d577e2b63f41f284a35a8dd5ce2489c618a9a9cd48c65b8a05",
        "b5bb1b8f6896d7a4c6b0d0e595e2b71dafdd759d85aa6d3ca6371707ac1467a1",
    },
}

# Sources from release 2.1.3, before per-command help and YouTube downloads.
_PRE_HELP_SOURCE_HASHES = {
    "app": "ff749fdbfe8a0337509612b46a4324aaf081355778048f519d2f9508d34630c2",
    "browser": "b1462695784f6221564c0d314af3ef6df27345bdc919c70da641ab6b97e8ade9",
    "capture": "2fbfa8cc5fa3ea0da183253963e630ff22dbd49d3d4c90d4678d70e41f3f6143",
    "cpp": "6d532eaef990f9bdfceae510d58bab5c42d2d25fa0a43fd0061d33cd0de7da39",
    "game": "662c73a70addfbd05c0f20cdc1e41db3060a229c1ef933539e9bd278beea7b4b",
    "git": "501cbe4a5335db87f85a0cd36ecd66ec65aa828cce9b264a6a880e1d6b66baad",
    "gpt": "d3173ac6e23c41acd60b311e4e9c9282831cec1e7716524b8e5a6f7da41ec29f",
    "lm": "a97d4d88d2bbf02971d999c95e93b16f63b14581b7765afcba8821f766fc54f2",
    "lofi": "e848ba5b972072af3a4ec949fdad5637fcbc31da020ed3b84251d3758ae84317",
    "mac": "519e0e2bf9e58797dce587e663bef76d72db5dd96a791d86d55ab1186106053a",
    "minecraft": "216ea401f929ede9ca0dbb49d728c195982d1513090f5fef00f9d17ec44d6444",
    "music": "3d96b1ed4cd85685119b7f52b76b1c7132e2c8118524eca00f05e71f70b23370",
    "netflix": "3420b878961c6660f1f1107469e0d2f2c32a1b2583e6a5d34e2b22d499b20088",
    "obsidian": "6ea9e20ea40bee08917df361cf1dbbc55ca1c7fdba01e1ac2959b68b007bcfb7",
    "py": "eb946afd8b4bcdd34cd43e3f8ae66f099ece29d6f410e29ea4818303b058096d",
    "rust": "15223569f5f416ac2bfbf685859cea545eeee1b3106132ec955b9fece4a5c038",
    "steam": "108d07567bbb4e760a9bf1ee0cca18ff7aa727a6c620b759e50caa8e9260efd9",
    "tg": "b38fc67ad385da929ec43048fd3839e43f983f4bd9304390de89bb4f96c1c883",
    "todo": "633f9fc925ec0d04c15853aeb9a65c964478379b24e960f78b9029f40c5c96ce",
    "work": "6ed6e3a9c6e65e69e7d15f409408191a432962c5da3c1d53cb81f276de1b1bf7",
    "yt": "a99712c19f8378ea9808eb4907c3c0500fb58ba02e1c35799165b64f817b5440",
    "zed": "2ce9028b831ef998d0552a919349be78558c0b46ea30ebdff5a21341dc6e240a"
}
for _name, _digest in _PRE_HELP_SOURCE_HASHES.items():
    LEGACY_SOURCE_HASHES.setdefault(_name, set()).add(_digest)

_HEADER = """# Unlaw command source. Edit freely: this file has no runtime dependency on Unlaw.
from __future__ import annotations
"""

_CONFIG_DEFAULTS: dict[str, dict[str, object]] = {
    "browser": {"apps": {"browser_url": "https://duckduckgo.com/"}},
    "capture": {
        "storage": {"root": "data"},
        "capture": {
            "camera_device": "0",
            "audio_device": "0",
            "screen_audio": True,
            "show_clicks": True,
        },
    },
    "cpp": {"projects": {"cpp": {"standard": 20, "initialize_git": False}}},
    "game": {"games": {"difficulty": "normal"}},
    "lm": {
        "lm": {
            "base_url": "http://127.0.0.1:1234/v1",
            "model": "auto",
            "system_prompt": "You are a concise and practical local assistant.",
            "temperature": 0.7,
            "timeout": 120,
        }
    },
    "lofi": {"apps": {"lofi_url": "https://lofi-engine.vercel.app/"}},
    "mac": {"mac": {"executable": "macos-harness", "timeout": 30}},
    "music": {"apps": {"spotify": "Spotify", "spotify_autoplay_delay": 2.0}},
    "py": {"projects": {"python": {"environment": "auto", "initialize_git": False}}},
    "rust": {"projects": {"rust": {"initialize_git": False}}},
    "tg": {
        "storage": {"root": "data"},
        "telegram": {
            "chat_id": "",
            "api_base": "https://api.telegram.org",
            "keychain_service": "unlaw.telegram",
        },
    },
    "todo": {
        "todo": {
            "vault_path": "~/aiwork/data-obsidian",
            "file": "TODO.md",
            "completed_column": "Completed",
        }
    },
    "work": {"apps": {"editor": "Zed", "lofi_url": "https://lofi-engine.vercel.app/"}},
    "yt": {"storage": {"root": "data"}, "apps": {"youtube_url": "https://www.youtube.com/"}},
    "zed": {"apps": {"editor": "Zed"}},
}

_CONFIG_SUPPORT = r'''
import copy
import os
import tomllib
from pathlib import Path


DEFAULT_CONFIG = __DEFAULT_CONFIG__


class ConfigError(ValueError):
    pass


def config_dir() -> Path:
    base = Path(os.environ.get("XDG_CONFIG_HOME", "~/.config")).expanduser()
    return base / "unlaw"


def _deep_merge(base: dict, override: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in override.items():
        result[key] = (
            _deep_merge(result[key], value)
            if isinstance(value, dict) and isinstance(result.get(key), dict)
            else copy.deepcopy(value)
        )
    return result


def load_config() -> dict:
    path = config_dir() / "config.toml"
    try:
        with path.open("rb") as handle:
            configured = tomllib.load(handle)
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise ConfigError(f"Could not read {path}: {error}") from error
    return _deep_merge(DEFAULT_CONFIG, configured)
'''

_TEMPLATES_SUPPORT = r'''
def templates_dir() -> Path:
    return config_dir() / "templates"
'''

_STORAGE_SUPPORT = r'''
def storage_path(*parts: str) -> Path:
    configured = Path(str(load_config()["storage"]["root"])).expanduser()
    root = configured if configured.is_absolute() else config_dir() / configured
    return root.joinpath(*parts)
'''

_CONFIG_WRITE_SUPPORT = r'''
import json
import tempfile


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    raise ConfigError(f"Unsupported configuration value: {value!r}")


def _serialize_table(table: dict, path: tuple[str, ...], lines: list[str]) -> None:
    if path:
        if lines and lines[-1] != "":
            lines.append("")
        lines.append("[" + ".".join(path) + "]")
    for key, value in table.items():
        if not isinstance(value, dict):
            lines.append(f"{key} = {_toml_value(value)}")
    for key, value in table.items():
        if isinstance(value, dict):
            _serialize_table(value, (*path, key), lines)


def set_config_value(dotted: str, value: object) -> None:
    config = load_config()
    parts = dotted.split(".")
    table = config
    for part in parts[:-1]:
        table = table.setdefault(part, {})
        if not isinstance(table, dict):
            raise ConfigError(f"Configuration key is not a table: {part}")
    table[parts[-1]] = value
    lines: list[str] = []
    _serialize_table(config, (), lines)
    root = config_dir()
    root.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=root, delete=False) as handle:
            handle.write("\n".join(lines).lstrip("\n") + "\n")
            handle.flush()
            os.fsync(handle.fileno())
            temporary = Path(handle.name)
        os.replace(temporary, root / "config.toml")
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()
'''

_LATEST_CAPTURE_SUPPORT = r'''
def latest_capture() -> Path | None:
    candidates = [
        path
        for directory in (
            storage_path("captures", "screenshots"),
            storage_path("captures", "recordings"),
        )
        if directory.is_dir()
        for path in directory.iterdir()
        if path.is_file()
    ]
    return max(candidates, key=lambda path: path.stat().st_mtime, default=None)
'''

_COMMAND_FILES: dict[str, tuple[str, ...]] = {
    "app": ("built_in_commands/app/main.py",),
    "browser": ("built_in_commands/browser/main.py",),
    "capture": ("capture.py",),
    "cpp": ("project_templates.py", "built_in_commands/cpp/main.py"),
    "game": ("games.py",),
    "git": ("built_in_commands/git/main.py",),
    "gpt": ("built_in_commands/gpt/main.py",),
    "lm": ("lmstudio.py",),
    "lofi": ("built_in_commands/lofi/main.py",),
    "mac": ("harness.py", "built_in_commands/mac/main.py"),
    "minecraft": ("built_in_commands/minecraft/main.py",),
    "music": ("desktop/music.py",),
    "netflix": ("built_in_commands/netflix/main.py",),
    "obsidian": ("built_in_commands/obsidian/main.py",),
    "py": ("project_templates.py", "built_in_commands/py/main.py"),
    "rust": ("project_templates.py", "built_in_commands/rust/main.py"),
    "steam": ("built_in_commands/steam/main.py",),
    "tg": ("telegram.py",),
    "todo": ("todo.py",),
    "work": ("desktop/work.py",),
    "yt": ("desktop/youtube.py",),
    "zed": ("built_in_commands/zed/main.py",),
}


def _support_source(name: str) -> str:
    parts: list[str] = []
    defaults = _CONFIG_DEFAULTS.get(name)
    if defaults is not None:
        rendered = pprint.pformat(defaults, sort_dicts=False, width=100)
        parts.append(_CONFIG_SUPPORT.replace("__DEFAULT_CONFIG__", rendered))
    if name in {"cpp", "py", "rust"}:
        parts.append(_TEMPLATES_SUPPORT)
    if name in {"capture", "tg", "yt"}:
        parts.append(_STORAGE_SUPPORT)
    if name == "tg":
        parts.extend((_CONFIG_WRITE_SUPPORT, _LATEST_CAPTURE_SUPPORT))
    return "\n\n".join(part.strip() for part in parts if part.strip())


def _clean_fragment(source: str, *, command: str) -> str:
    removed_prefixes = (
        "from __future__ import annotations",
        "from unlawful.command_help import ",
        "from .config import ",
        "from unlawful.config import ",
        "from unlawful.project_templates import ",
        "from unlawful import harness",
        "from .capture import latest_capture",
    )
    lines = [line for line in source.splitlines() if not line.lstrip().startswith(removed_prefixes)]
    text = "\n".join(lines).strip() + "\n"
    text = text.replace(f"COMMAND_HELP[{command!r}]", "COMMAND_HELP").replace(
        f'COMMAND_HELP["{command}"]', "COMMAND_HELP"
    )
    if command == "mac":
        text = text.replace("harness.see", "see").replace("harness.key", "key")
        text = text.replace("harness.type_text", "type_text").replace("harness.click", "click")
    return text


def command_source(name: str) -> str:
    """Return the complete focused source installed for one default command."""
    try:
        paths = _COMMAND_FILES[name]
    except KeyError as error:
        raise ValueError(f"Unknown default command: {name}") from error
    fragments = [
        _clean_fragment((_ROOT / relative).read_text(encoding="utf-8"), command=name)
        for relative in paths
    ]
    sections = [_HEADER, f"COMMAND_HELP = {COMMAND_HELP[name]!r}", _support_source(name), *fragments]
    return "\n\n".join(section.strip() for section in sections if section.strip()) + "\n"


def is_legacy_wrapper(source: str, name: str) -> bool:
    return source.strip() == (
        f"from unlawful.built_in_commands.{name}.main import main\n\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())"
    ) or source.strip() == (
        f"from unlawful.built_in_commands.{name}.main import main\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())"
    )


def is_replaceable_command_source(source: str, name: str) -> bool:
    digest = hashlib.sha256(source.encode()).hexdigest()
    return is_legacy_wrapper(source, name) or digest in LEGACY_SOURCE_HASHES.get(name, set())
